### ISSUE TITLE
const.HTTP_* status constants have been removed from HA

### ISSUE THREAD

**Issue by robbrad** [robmarkcole/HASS-Machinebox-Classificationbox#6]
See: https://github.com/home-assistant/core/pull/58380/commits/fbb7c3136847a42339965614013e7a7014fb946b

Issue here :
https://github.com/robmarkcole/HASS-Machinebox-Classificationbox/blob/master/custom_components/classificationbox/image_processing.py#L19

Hard coding in the status codes makes it work again - without logic changes

**Comment by robbrad** [comment]
https://docs.python.org/3/library/http.html#http.HTTPStatus is being used as an alternative

**Comment by robbrad** [comment]
https://github.com/home-assistant/architecture/discussions/548

**Comment by robmarkcole** [comment]
@robbrad I am happy to hard code - could you create a PR to do this? Many thanks

**Comment by robbrad** [comment]
Done :)

**Comment by robmarkcole** [comment]
thanks!
